### ISSUE TITLE
Question: Is there a way to prevent electron exit due to obs crash

### ISSUE THREAD

**Issue by rosendolu** [streamlabs/obs-studio-node#1462]
## versions:

Microsoft Windows 11 
[01]: Intel64 Family 6 Model 154 Stepping 3 GenuineIntel ~2500 Mhz

```
chrome: "118.0.5993.120"
electron: "27.0.3"
node: "18.17.1"
obs-studio-node: "osn-0.15.6-release-win64.tar.gz"
```
## Repreduce:

Clone repo [https://github.com/Envek/obs-studio-node-example](https://github.com/Envek/obs-studio-node-example) (thanks for Envek).  Start the app,kill `obs64.exe`, the app quit unexpectly

**Comment by summeroff** [comment]
I'm unsure if this is an exit or a crash. In Electron your js code should receive an error on js calls if there's no OBS process. It's possible that it exits by crashing. We haven't tested this specific scenario with OSN, so crashing is a possibility.

The emergency exit was intentionally introduced because recovering isn't possible due to our current approach to keeping data synchronized between the OBS process, OSN node module inside Electron, and JS frontend.
And, for greater reliability, we've implemented a separate process that watches over both OBS and Electron processes to detect crashes and kill remaining processes, preventing zombies and resource leaks.

If recovery isn't required, and your UX is designed to let the user continue working even without an OBS process (e.g., to save changes or send a report), then it might be possible. However, you'll need to fix the underlying issue causing the exit. In case of crash you should see a stack trace if you attach a Visual Studio debugger to the Electron process before it exits.

**Comment by rosendolu** [comment]
Thank you ,appreciate your advice.
